# Generated by Django 2.0.4 on 2018-04-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=250)),
                ('account_id', models.IntegerField(default=0)),
                ('account_child_id', models.IntegerField(default=0)),
                ('potential', models.CharField(max_length=250)),
                ('pipeline', models.CharField(max_length=250)),
                ('stage', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AccountRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(default=0)),
                ('account_name', models.CharField(max_length=250)),
                ('customer_name', models.CharField(max_length=250)),
                ('account_risk', models.TextField()),
            ],
        ),
    ]
