# Generated by Django 2.0.4 on 2018-04-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_name',
        ),
    ]
